### ISSUE TITLE
Typo in body and p example 

### ISSUE THREAD

**Issue by laramontana** [learn-co-curriculum/js-dom-and-events-css-refresher-readme#2]
> The solution is: 24px font size, and a red color. <...> It effectively overwrites its inherited font-size property with its own value.

I assume it was meant to be: "It effectively overwrites its inherited _**color**_ property with its own value." Inherited blue was overwritten with its own red

**Comment by cjbrock** [comment]
You are absolutely correct! It should be `color`, not `font-size`. Thanks for catching that - it should be fixed. 

// <3 Corinna
