### ISSUE TITLE
'color', not 'font-size' property

### ISSUE THREAD

**Issue by sebge-1** [learn-co-curriculum/js-dom-and-events-css-refresher-readme#3]
Referring to this text: 

> The ruleset for making <p> red has precedence, since its selector is more specific. It effectively overwrites its inherited font-size property with its own value.

It should talk about the 'color' property, since font-size is never overwritten in the example but inherited.

**Comment by cjbrock** [comment]
You are absolutely correct! It should be `color`, not `font-size`. Thanks for catching that - it should be fixed. 

// <3 Corinna
