### ISSUE TITLE
Rewrite this sentence for clarity

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-dom-and-events-css-refresher-readme#4]
This sentence is confusing: "Selecting DOM nodes in JS to work with uses CSS selectors, so it's important to know how these work!"

Here is a suggested rewrite:
In JS, we select DOM nodes using CSS selectors, so it's important to know how these work!

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback as always, we have updated the materials.
