### ISSUE TITLE
This should be two sentences

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-dom-and-events-css-refresher-readme#5]
This is a run-on sentence:
"Let's select another element, this time we want to select any .big elements, as well as any <p> tags inside an element with the red class:"

I suggest splitting it into two sentences as follows:
Let's select another element. This time, we want to select any .big elements, as well as any <p> tags inside an element with the red class:"

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback. We've updated the materials.
